name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aady12/ubuntu:0.0.1
    - name: Push to Dockerhub
      run: docker push aady12/ubuntu:0.0.1
    - name: Triggring spinnaker workflow
      run: |
        curl http://a02be9406d91144149d3f5bed363c6cd-1098001009.ap-south-1.elb.amazonaws.com/webhooks/webhook/testing -X POST -H "content-type: application/json" -d "{ \"key\": \"value\" }"